### ISSUE TITLE
I can't logoff 

### ISSUE THREAD

**Issue by ShlomiPorush** [pwrtelegram/pwrtelegram-app#14]
After I changed the bot token I can't log off... I m getting a white panel

**Comment by ShlomiPorush** [comment]
Here is a screen shot http://jpg.1012.co.il/view.php?p=14723995149045

**Comment by aRandomStranger** [comment]
_Hi there,_

Please go to the App Details in your settings and try to clear the cache.
![android-settings-application-manager-app-info-clear-data](https://cloud.githubusercontent.com/assets/17005025/18034881/fb292ba8-6d48-11e6-8b6e-85dd6702b9df.png)

This should reset the app and you should be able to use a other token.

Best regards
- aRandomStranger

**Comment by ShlomiPorush** [comment]
I already tried this.. By clicking on Clear data it opens the telegram cache Settings

**Comment by aRandomStranger** [comment]
It shouldn't. Please try to open it in your system settings.

**Comment by wfjsw** [comment]
@0120139 Hmm Telegram did implement this. You may use other method.

**Comment by ShlomiPorush** [comment]
Anyway CCleaner did the job.. All good now

**Comment by aRandomStranger** [comment]
@0120139 Nice to see.

**Comment by danog** [comment]
I'm glad you found a workaround, but I'm still interested in this issue. What device/os are you using? Could you try logging in, logging out and then sending me the logs (/sdcard/Android/data/xyz.pwrtelegram.messenger/files/logs)? Thanks.

**Comment by ShlomiPorush** [comment]
Sure.. I m on a Nexus 6P with CM 
Here are the logs.. https://we.tl/L8rSaX4mij

Help this helps you
