### ISSUE TITLE
is possible to change name or username or photo of account with pwrtelegram api?

### ISSUE THREAD

**Issue by ghost** [pwrtelegram/pwrtelegram-app#19]
hi
i want to login telegram account with api and it is OK
but is possible to change name of account or username of accont or photo
with this api ??
thanks

**Comment by ghost** [comment]
@saeedata It should be (but only for users, not bots of course)
Check the account.updateProfile method

**Comment by ghost** [comment]
Thank for answer 
But i cant find this method 
May you get me a direct link about this method 
Thnaks

**Comment by danog** [comment]
PLEASE read the docs before opening an issue.
The account.updateProfile allows you to set a bio too btw.
