### ISSUE TITLE
Question, how can the app know when the message is read?

### ISSUE THREAD

**Issue by zarEclEC** [pwrtelegram/pwrtelegram-app#22]
![Screenshot_20191007-101143_PWRTelegram](https://user-images.githubusercontent.com/6240983/66295294-3d01d680-e8eb-11e9-9633-b64265c1b4f3.png)

Which api does it uses? Thanks!

**Comment by danog** [comment]
It uses the [MTProto API](https://docs.madelineproto.xyz)
