### ISSUE TITLE
Fix deleting of messages

### ISSUE THREAD

**Issue by danog** [pwrtelegram/pwrtelegram-app#7]
Fix deleting of messages

**Comment by LucentW** [comment]
@danog You can't really delete messages since on del_msg, you get BOT_METHOD_INVALID, you might just hide the option temporarily until Telegram adds that to the REST API and should be unlocked to MTProto clients too.

**Comment by danog** [comment]
Tru dat. I forgot the official API isn't as cool as mine :D
